version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3003:3003"
    restart: always
    networks:
      - api_default

networks:
  api_default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.1.0/24