-- Módulo Expedição: bordero de etiquetagem para impressora Zebra
-- Substitui a tabela legada `exp_bordero` do MySQL. Armazena uma linha por
-- volume (001/003, 002/003...) para alimentar o CSV do configurador Zebra.
USE Intranet;
GO

IF OBJECT_ID('dbo.TAB_EXP_BORDERO','U') IS NULL
BEGIN
  CREATE TABLE dbo.TAB_EXP_BORDERO (
    ID              INT IDENTITY(1,1) PRIMARY KEY,
    NOTAFISCAL      VARCHAR(20)  NOT NULL,
    SERIE           VARCHAR(4)   NULL,
    DESTINATARIO    NVARCHAR(200) NULL,
    ENDERECO        NVARCHAR(300) NULL,
    CIDADE          NVARCHAR(150) NULL,
    CEP             VARCHAR(12)  NULL,
    TRANSPORTADORA  NVARCHAR(200) NULL,
    VOLUMES         VARCHAR(10)  NOT NULL,   -- '001/010'
    ID_USER         INT          NULL,
    CRIADO_EM       DATETIME     NOT NULL CONSTRAINT DF_EXP_BORD_DT DEFAULT (GETDATE())
  );
  CREATE INDEX IX_EXP_BORD_NF ON dbo.TAB_EXP_BORDERO (NOTAFISCAL);
  PRINT '  -> TAB_EXP_BORDERO criada.';
END
ELSE PRINT '  -> TAB_EXP_BORDERO ja existe.';
GO

IF NOT EXISTS (SELECT 1 FROM dbo.TAB_INTRANET_PERMISSOES WHERE ID_PERMISSAO = 12001)
  INSERT INTO dbo.TAB_INTRANET_PERMISSOES (ID_PERMISSAO, NOME, MODULO) VALUES (12001, 'Expedicao - Notas a Expedir', 'Expedicao');
IF NOT EXISTS (SELECT 1 FROM dbo.TAB_INTRANET_PERMISSOES WHERE ID_PERMISSAO = 12002)
  INSERT INTO dbo.TAB_INTRANET_PERMISSOES (ID_PERMISSAO, NOME, MODULO) VALUES (12002, 'Expedicao - Bordero de Etiquetagem', 'Expedicao');

DECLARE @u INT; SELECT @u = ID FROM dbo.TAB_INTRANET_USR WHERE EMAIL = 'admin@gnatus.com.br';
IF @u IS NOT NULL
BEGIN
  IF NOT EXISTS (SELECT 1 FROM dbo.TAB_INTRANET_USR_PERMISSOES WHERE ID_USER=@u AND ID_PERMISSAO=12001)
    INSERT INTO dbo.TAB_INTRANET_USR_PERMISSOES (ID_USER, ID_PERMISSAO, MATRICULA) VALUES (@u, 12001, 'ADM001');
  IF NOT EXISTS (SELECT 1 FROM dbo.TAB_INTRANET_USR_PERMISSOES WHERE ID_USER=@u AND ID_PERMISSAO=12002)
    INSERT INTO dbo.TAB_INTRANET_USR_PERMISSOES (ID_USER, ID_PERMISSAO, MATRICULA) VALUES (@u, 12002, 'ADM001');
END
GO

PRINT 'Modulo Expedicao: setup concluido.';
