-- =============================================
-- Queries Úteis para Consultar Histórico Completo SZB010
-- =============================================

-- 1. LISTAR TODO O HISTÓRICO DE UM CONTRATO/PROPOSTA ESPECÍFICO
-- =============================================
SELECT 
    HIST_ID,
    HIST_DATA_ALTERACAO,
    HIST_USUARIO,
    HIST_OPERACAO,
    ZB_FILIAL,
    ZB_FLUIG AS PROPOSTA,
    ZB_CODCLI AS CLIENTE,
    ZB_NOME,
    ZB_MALT,
    ZB_STATUS_ENG,
    ZB_X_KWP
FROM [dbo].[SZB_HISTORICO_COMPLETO]
WHERE ZB_FLUIG = '00339129' -- Substituir pelo número da proposta
ORDER BY HIST_DATA_ALTERACAO DESC;

-- 2. LISTAR ALTERAÇÕES RECENTES (ÚLTIMAS 24 HORAS)
-- =============================================
SELECT 
    HIST_ID,
    HIST_DATA_ALTERACAO,
    HIST_USUARIO,
    HIST_OPERACAO,
    ZB_FILIAL,
    ZB_FLUIG AS PROPOSTA,
    ZB_NOME AS CLIENTE,
    ZB_MALT,
    ZB_STATUS_ENG
FROM [dbo].[SZB_HISTORICO_COMPLETO]
WHERE HIST_DATA_ALTERACAO >= DATEADD(HOUR, -24, GETDATE())
ORDER BY HIST_DATA_ALTERACAO DESC;

-- 3. ESTATÍSTICAS DE ALTERAÇÕES POR USUÁRIO
-- =============================================
SELECT 
    HIST_USUARIO,
    COUNT(*) AS TOTAL_ALTERACOES,
    MIN(HIST_DATA_ALTERACAO) AS PRIMEIRA_ALTERACAO,
    MAX(HIST_DATA_ALTERACAO) AS ULTIMA_ALTERACAO
FROM [dbo].[SZB_HISTORICO_COMPLETO]
GROUP BY HIST_USUARIO
ORDER BY TOTAL_ALTERACOES DESC;

-- 4. ESTATÍSTICAS DE ALTERAÇÕES POR DIA
-- =============================================
SELECT 
    CAST(HIST_DATA_ALTERACAO AS DATE) AS DIA,
    COUNT(*) AS TOTAL_ALTERACOES
FROM [dbo].[SZB_HISTORICO_COMPLETO]
GROUP BY CAST(HIST_DATA_ALTERACAO AS DATE)
ORDER BY DIA DESC;

-- 5. LISTAR TODAS AS ALTERAÇÕES DE UM CLIENTE ESPECÍFICO
-- =============================================
SELECT 
    HIST_ID,
    HIST_DATA_ALTERACAO,
    HIST_USUARIO,
    HIST_OPERACAO,
    ZB_FILIAL,
    ZB_FLUIG AS PROPOSTA,
    ZB_CODCLI AS COD_CLIENTE,
    ZB_NOME AS NOME_CLIENTE,
    ZB_MALT,
    ZB_STATUS_ENG
FROM [dbo].[SZB_HISTORICO_COMPLETO]
WHERE ZB_CODCLI = '107607' -- Substituir pelo código do cliente
ORDER BY HIST_DATA_ALTERACAO DESC;

-- 6. REGISTRO COMPLETO - Ver TODOS os dados do momento da alteração
-- =============================================
SELECT 
    HIST_ID,
    HIST_DATA_ALTERACAO,
    HIST_USUARIO,
    HIST_OPERACAO,
    * -- Retorna TODAS as colunas
FROM [dbo].[SZB_HISTORICO_COMPLETO]
WHERE ZB_FLUIG = '00339129' -- Substituir pelo número da proposta
ORDER BY HIST_DATA_ALTERACAO DESC;

-- 7. TIMELINE DE ALTERAÇÕES - Visão cronológica com versões
-- =============================================
SELECT 
    ROW_NUMBER() OVER (PARTITION BY ZB_FLUIG ORDER BY HIST_DATA_ALTERACAO) AS VERSAO,
    ZB_FILIAL,
    ZB_FLUIG AS PROPOSTA,
    ZB_MALT AS VALOR_MALT,
    ZB_STATUS_ENG,
    ZB_NOME AS CLIENTE,
    HIST_DATA_ALTERACAO,
    HIST_USUARIO,
    HIST_OPERACAO,
    DATEDIFF(MINUTE, 
        LAG(HIST_DATA_ALTERACAO) OVER (PARTITION BY ZB_FLUIG ORDER BY HIST_DATA_ALTERACAO),
        HIST_DATA_ALTERACAO
    ) AS MINUTOS_DESDE_ULTIMA_ALT
FROM [dbo].[SZB_HISTORICO_COMPLETO]
WHERE ZB_FLUIG = '00339129' -- Substituir pelo número da proposta
ORDER BY HIST_DATA_ALTERACAO;

-- 8. PROPOSTAS COM MAIS ALTERAÇÕES
-- =============================================
SELECT TOP 20
    ZB_FLUIG AS PROPOSTA,
    ZB_FILIAL,
    MAX(ZB_NOME) AS CLIENTE,
    COUNT(*) AS TOTAL_ALTERACOES,
    MIN(HIST_DATA_ALTERACAO) AS PRIMEIRA_ALTERACAO,
    MAX(HIST_DATA_ALTERACAO) AS ULTIMA_ALTERACAO,
    STRING_AGG(ZB_MALT, ' -> ') WITHIN GROUP (ORDER BY HIST_DATA_ALTERACAO) AS SEQUENCIA_VALORES
FROM [dbo].[SZB_HISTORICO_COMPLETO]
GROUP BY ZB_FLUIG, ZB_FILIAL
ORDER BY TOTAL_ALTERACOES DESC;

-- 9. ALTERAÇÕES POR FILIAL
-- =============================================
SELECT 
    ZB_FILIAL,
    COUNT(*) AS TOTAL_ALTERACOES,
    COUNT(DISTINCT ZB_FLUIG) AS PROPOSTAS_DISTINTAS,
    MIN(HIST_DATA_ALTERACAO) AS PRIMEIRA_ALTERACAO,
    MAX(HIST_DATA_ALTERACAO) AS ULTIMA_ALTERACAO
FROM [dbo].[SZB_HISTORICO_COMPLETO]
GROUP BY ZB_FILIAL
ORDER BY ZB_FILIAL;

-- 10. COMPARAR VERSÕES - Ver diferenças entre versões
-- =============================================
WITH Versoes AS (
    SELECT 
        ROW_NUMBER() OVER (PARTITION BY ZB_FLUIG ORDER BY HIST_DATA_ALTERACAO) AS VERSAO,
        *
    FROM [dbo].[SZB_HISTORICO_COMPLETO]
    WHERE ZB_FLUIG = '00339129' -- Substituir pelo número da proposta
)
SELECT 
    V1.VERSAO AS VERSAO_ANTERIOR,
    V2.VERSAO AS VERSAO_ATUAL,
    V1.ZB_MALT AS MALT_ANTERIOR,
    V2.ZB_MALT AS MALT_ATUAL,
    V1.ZB_STATUS_ENG AS STATUS_ENG_ANTERIOR,
    V2.ZB_STATUS_ENG AS STATUS_ENG_ATUAL,
    V1.ZB_X_KWP AS KWP_ANTERIOR,
    V2.ZB_X_KWP AS KWP_ATUAL,
    V2.HIST_DATA_ALTERACAO,
    V2.HIST_USUARIO,
    DATEDIFF(MINUTE, V1.HIST_DATA_ALTERACAO, V2.HIST_DATA_ALTERACAO) AS MINUTOS_ENTRE_VERSOES
FROM Versoes V1
INNER JOIN Versoes V2 ON V2.VERSAO = V1.VERSAO + 1
ORDER BY V2.VERSAO;

-- 11. AUDITORIA COMPLETA - Todas as alterações com todos os dados
-- =============================================
SELECT 
    HIST_ID,
    HIST_DATA_ALTERACAO,
    HIST_USUARIO,
    HIST_HOST,
    HIST_OPERACAO,
    ZB_FILIAL,
    ZB_FLUIG AS PROPOSTA,
    ZB_NOME AS CLIENTE,
    ZB_MUN AS CIDADE,
    ZB_EST AS UF,
    ZB_MALT,
    ZB_STATUS_ENG,
    ZB_X_KWP AS KWP,
    ZB_INVERS AS INVERSOR,
    ZB_PLACA
FROM [dbo].[SZB_HISTORICO_COMPLETO]
ORDER BY HIST_DATA_ALTERACAO DESC;
